version: "2"
services:
  mongodb:
    image: mongo:3.2
    container_name: mongodb
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: mongodb
    expose:
      - "27017"
    ports:
      - 27016:27017
    volumes:
      - /var/lib/mongodb:/data/db

# gargantua:
#   image: ppcelery/laisky-blog
#   container_name: gargantua
#   logging:
#     driver: syslog
#     options:
#       tag: gargantua
#   links:
#     - mongodb:mongodb
#   ports:
#     - 27851:27850
#   command: \
#     --port=27850 \
#     --dbhost=mongodb \
#     --dbport=27017 \
#     --debug=false \
#     --mail_passwd=YOUR_GMAIL_PASSWORD

networks:
  default:
    driver: bridge
