server {
    listen 80;

    gzip on;
    # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_vary on;

    root /app;
    index index.html;

    location ^~ /assets/ {
        expires max;
        add_header Cache-Control "public, immutable, no-transform";
        try_files $uri =404;
    }

    location / {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri $uri/ /index.html;
    }
}
