version: "2"
services:
  mongodb:
    image: mongo:3.2
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: mongodb
    networks:
      - gargantua
    ports:
      - 127.0.0.1:27016:27017
    volumes:
      - /var/lib/mongodb:/data/db

  fluentd:
    image: ppcelery/fluentd-docker-image
    restart: always
    networks:
      - gargantua
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: fluentd
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /var/lib/fluentd:/fluentd/log
      - /etc/fluentd:/fluentd/etc
    links:
      - mongodb:mongodb
    ports:
      - 127.0.0.1:24224:24224

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    networks:
      - gargantua
    logging:
      driver: syslog
      options:
        syslog-facility: local6
        tag: fluentd
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080

  # gargantua:
  #   image: ppcelery/laisky-blog
  #   restart: always
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: "127.0.0.1:24224"
  #       tag: "gargantua"
  #   links:
  #     - mongodb:mongodb
  #   networks:
  #     - gargantua
  #   expose:
  #     - "27850"
  #   ports:
  #     - 127.0.0.1:27851:27850
  #   command:
  #     - "python"
  #     - "-m"
  #     - "gargantua"
  #     - "--port=27850"
  #     - "--dbhost=mongodb"
  #     - "--dbport=27017"
  #     - "--debug=false"
  #     - "--mail_host=smtp.mailgun.org"
  #     - "--mail_port=25"
  #     - "--mail_subject=Gargantua Error"
  #     - "--mail_from_addr=gargantua@laisky.com"
  #     - "--mail_to_addrs='ppcelery@gmail.com'"
  #     - "--mail_username=<YOUR_SMTP_USERNAME"
  #     - "--mail_passwd=<YOUR_SMTP_PASSWORD>"

networks:
  gargantua:
    driver: bridge
